# Generated by Django 5.1.6 on 2025-02-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FarmManager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cow",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="farm",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
