# Generated by Django 5.1.6 on 2025-02-25 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FarmManager", "0002_cow_is_deleted_farm_is_deleted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="breedtype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="feedingfrequency",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="floortype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="generalhealthstatus",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="gynecologicalstatus",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="housingtype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="mastitisstatus",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="udderhealthstatus",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="watersource",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="farm",
            name="number_of_milking_cow",
        ),
        migrations.AddField(
            model_name="doctor",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="farm",
            name="number_of_milking_cows",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of milking cows",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="farmermedicalreport",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="inseminationrecord",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="inseminator",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="medicalassessment",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reproduction",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="breedtype",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="cow",
            name="bcs",
            field=models.DecimalField(
                choices=[
                    (1.0, "1.0"),
                    (1.5, "1.5"),
                    (2.0, "2.0"),
                    (2.5, "2.5"),
                    (3.0, "3.0"),
                    (3.5, "3.5"),
                    (4.0, "4.0"),
                    (4.5, "4.5"),
                    (5.0, "5.0"),
                ],
                decimal_places=1,
                max_digits=2,
                verbose_name="Body Condition Score",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="phone_number",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number (e.g. +251912345678 or 0912345678)",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="farm_hygiene_score",
            field=models.PositiveIntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4")],
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="number_of_calves",
            field=models.PositiveIntegerField(
                help_text="Number of calves",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="telephone_number",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number (e.g. +251912345678 or 0912345678)",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="total_daily_milk",
            field=models.PositiveIntegerField(
                help_text="Total daily milk production in liters",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="total_number_of_cows",
            field=models.PositiveIntegerField(
                help_text="Total number of cows",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="inseminator",
            name="phone_number",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number (e.g. +251912345678 or 0912345678)",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
    ]
