# Generated by Django 5.1 on 2025-03-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FarmManager", "0004_alter_reproduction_heat_sign_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reproduction",
            name="heat_signs_seen",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
