# Generated by Django 5.2 on 2025-04-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FarmManager", "0006_alter_reproduction_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cow",
            name="age_in_days",
        ),
        migrations.AddField(
            model_name="cow",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicalassessment",
            name="has_lameness",
            field=models.BooleanField(
                default=False, help_text="Whether the cow shows signs of lameness"
            ),
        ),
    ]
