# Generated by Django 5.2 on 2025-10-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FarmManager", "0007_remove_cow_age_in_days_cow_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="cluster_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Cluster identifier for grouping farms",
                max_length=50,
                null=True,
            ),
        ),
    ]
