"""
Django settings for FarmManagerSystem project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-^nvczssod(!rcglw2)dhy)looo$0$ssiydr4_ok&1_82esqt7+",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "*").split(",")


# Application definition

INSTALLED_APPS = [
    # "unfold",  # Unfold admin - disabled due to compatibility issues
    # "unfold.contrib.filters",
    # "unfold.contrib.forms",
    # "unfold.contrib.inlines",
    # "unfold.contrib.import_export",
    # "unfold.contrib.guardian",
    # "unfold.contrib.simple_history",
    "django.contrib.admin",
    "FarmManager",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_yasg",
    "corsheaders",
    "django_filters",
    "AlertSystem",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "FarmManager.middleware.RequestTimeoutMiddleware",  # Request timeout enforcement
    "FarmManager.middleware.PerformanceMonitoringMiddleware",  # Performance tracking
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Request timeout settings
REQUEST_TIMEOUT = 30  # Maximum time (seconds) for a request to complete
ENABLE_REQUEST_TIMEOUT = True  # Enable/disable request timeout middleware
SLOW_REQUEST_THRESHOLD = 2.0  # Log warning for requests slower than this (seconds)
QUERY_COUNT_WARNING_THRESHOLD = 20  # Warn if query count exceeds this

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = [
    "https://cowsville-aau-cvma.com",
    "https://www.cowsville-aau-cvma.com",
    "http://localhost:8000",
    "http://localhost:3000",
]

# CSRF Trusted Origins (Important for POST/PUT requests)
CSRF_TRUSTED_ORIGINS = [
    "https://cowsville-aau-cvma.com",
    "https://www.cowsville-aau-cvma.com",
    "http://localhost:3000",
]

ROOT_URLCONF = "FarmManagerSystem.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "FarmManagerSystem/templates/farmManager"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # "unfold.context_processors.unfold",
            ],
        },
    },
]

WSGI_APPLICATION = "FarmManagerSystem.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
        "CONN_MAX_AGE": 60,
    }
}

# Caching Configuration
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "farmmanager-cache",
        "TIMEOUT": 300,  # 5 minutes default timeout
        "OPTIONS": {"MAX_ENTRIES": 1000},
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (user uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Comment out non-existent static directory
# STATICFILES_DIRS = [
#     BASE_DIR / "FarmManagerSystem/myapp/static",
# ]


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": "logs/farm_manager.log",  # Make sure this directory exists
            "formatter": "verbose",
        },
    },
    "loggers": {
        "FarmManager": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": True,
        },
        # Add specific loggers for important modules
        "FarmManager.views": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
}

# APScheduler settings have been removed since we're using MemoryJobStore

# Django REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # Pagination settings - prevents returning all records at once
    "DEFAULT_PAGINATION_CLASS": "FarmManager.pagination.StandardResultsSetPagination",
    "PAGE_SIZE": 50,  # Default page size (can be overridden via ?page_size=)
    # Filtering backends
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    # Throttling to prevent abuse
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",  # Anonymous users: 100 requests per hour
        "user": "1000/hour",  # Authenticated users: 1000 requests per hour
    },
    # Renderer settings
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
}


# UNFOLD = {
#     "site_title": "Cowsville Management",
#     "site_header": "Cowsville Admin",
#     "site_logo": "icons/logo.svg",
#     "show_history": True,
#     "collapsible_menu": True,
#     "colors": {
#         "primary": "#134B73",
#     },
# }
UNFOLD = {
    "SITE_TITLE": "Cowsville Admin",
    "SITE_HEADER": "Cowsville Management",
    "SITE_URL": "/admin/",
    "SITE_ICON": {
        "light": "/static/icons/cowsville-logo.svg",
        "dark": "/static/icons/cowsville-logo.svg",
    },

    # "THEME": "light",
    "COLLAPSIBLE_SIDEBAR": True,
    "COLORS": {
        "primary": {
            50:  "#e6f0ff",
            100: "#bad3ff",
            200: "#89b9ff",
            300: "#589eff",
            400: "#2d84ff",
            500: "#006aff",
            600: "#0053cc",
            700: "#003d99",
            800: "#002666",
            900: "#001033"
        }
    },

    "SIDEBAR": {
        "show_search": True,
        "show_all_models": False,
        "show_app_icons": True,
        "icons": {},
    },

    "LOGIN": {
        "language_selector": False,
        "logo": {
            "light": "/static/icons/cowsville-logo.svg",
            "dark": "/static/icons/cowsville-logo.svg",
        },
        "image": lambda request: "/static/icons/cowsville-logo.svg",
        "subtitle": "Farm & Vet Management Login",
    },
}
